"""empty message

Revision ID: 672186f74ed7
Revises: 1790155f200b
Create Date: 2020-07-13 14:04:20.321794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672186f74ed7'
down_revision = '1790155f200b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
